Repository mayaleng/engine, pull requests merged in 2020-06, with the labels that each got.

#9 Feature/crud words
  internal/translator/data/languages.go
  internal/translator/data/languages_test.go
  internal/translator/data/words.go
  internal/translator/data/words_test.go
Labels: bug, enhancement

#10 Feature/read rules
  internal/translator/data/languages.go
  internal/translator/data/languages_test.go
  internal/translator/data/rules.go
  internal/translator/data/rules_test.go
  internal/translator/data/words.go
  internal/translator/default.go
  internal/translator/linguakit/parser.go
  internal/translator/linguakit/word.go
  internal/translator/rules.go
  internal/translator/translator.go
Labels: enhancement

#11 feat(packages): Refactoring data package
  cmd/httpd/internal/handlers/api.go
  internal/platform/data/doc.go
  internal/platform/data/fixtures/rule.json
  internal/platform/data/languages.go
  internal/platform/data/languages_test.go
  internal/platform/data/rules.go
  internal/platform/data/rules_test.go
  internal/platform/data/test.go
  internal/platform/data/translations.go
  internal/platform/data/translations_test.go
  internal/platform/data/words.go
  internal/platform/data/words_test.go
  internal/translator/data/translations.go
  internal/translator/data/words_test.go
  internal/translator/rules.go
  internal/translator/translator.go
  test.sh
Labels: enhancement

#12 feat(packages): Refactoring package structure
  cmd/httpd/internal/handlers/api.go
  cmd/httpd/internal/handlers/translations.go
  cmd/httpd/main.go
  internal/platform/data/fixtures/rule.json
  internal/platform/data/test.go
  internal/platform/linguakit/client.go
  internal/platform/linguakit/client_test.go
  internal/platform/linguakit/doc.go
  internal/platform/linguakit/parser.go
  internal/platform/linguakit/parser_test.go
  internal/platform/linguakit/sentence.go
  internal/platform/linguakit/word.go
  internal/platform/types/doc.go
  internal/platform/types/envs.go
  internal/platform/types/translations.go
  internal/translator/common.go
  internal/translator/default.go
  internal/translator/direct.go
  internal/translator/rules.go
  internal/translator/translator.go
  internal/translator/types.go
  internal/translator/utils/rules.go
  internal/translator/utils/templates.go
Labels: enhancement

#13 feat(tests): Adding component tests
  internal/translator/test/languages.go
  internal/translator/test/rules.go
  internal/translator/test/translations.go
  internal/translator/test/word.go
  internal/translator/translator_test.go
Labels: enhancement, tests

#18 feat(templates): Conditional templates
  docs/algorithm.md
  internal/platform/data/rules.go
  internal/platform/data/rules_test.go
  internal/translator/test/rules.go
  internal/translator/test/word.go
  internal/translator/translator_test.go
  internal/translator/utils/rules_test.go
  internal/translator/utils/templates.go
  internal/translator/utils/templates_test.go
  run.sh
  test.sh
Labels: enhancement

#20 chore(tests): Improving translation tests
  internal/translator/test/rules.go
  internal/translator/test/word.go
  internal/translator/translator_test.go
Labels: tests

#19 Feature/filter rules
  docs/algorithm.md
  internal/platform/data/rules_test.go
  internal/translator/translator.go
  internal/translator/utils/rules.go
  internal/translator/utils/rules_test.go
Labels: enhancement

#22 feat(http-api): CRUD for words
  cmd/httpd/handlers/api.go
  cmd/httpd/handlers/doc.go
  cmd/httpd/handlers/engine.go
  cmd/httpd/handlers/words.go
  cmd/httpd/internal/handlers/response.go
  cmd/httpd/main.go
  go.mod
  go.sum
  internal/platform/data/languages.go
  internal/platform/data/options.go
  internal/platform/data/words.go
  internal/platform/data/words_test.go
  internal/platform/web/decode.go
  internal/platform/web/decode_test.go
  internal/platform/web/errors.go
  internal/platform/web/errors_test.go
  internal/platform/web/pagination.go
  internal/platform/web/pagination_test.go
  internal/platform/web/response.go
  internal/platform/web/response_test.go
  internal/translator/test/word.go
  internal/translator/translator_test.go
Labels: enhancement

#23 More information to know how to write rules
  README.md
  docs/rulesresources.md
  internal/translator/rules.go
  internal/translator/test/rules.go
  internal/translator/translator_test.go
Labels: documentation

#24 Feature/refactor rules
  internal/translator/test/rules.go
Labels: tests

#25 Feature/languages api
  cmd/httpd/handlers/api.go
  cmd/httpd/handlers/languages.go
  internal/platform/data/languages.go
  internal/platform/data/languages_test.go
Labels: enhancement

#26 feature(api-rules): API CRUD for rules
  README.md
  cmd/httpd/handlers/api.go
  cmd/httpd/handlers/rules.go
  cmd/httpd/handlers/words.go
  docs/MayaLeng.postman_collection.json
  go.mod
  go.sum
  internal/platform/data/languages.go
  internal/platform/data/rules.go
  internal/platform/data/rules_test.go
  internal/platform/data/words.go
  internal/platform/web/decode.go
  internal/translator/test/rules.go
  internal/translator/translator.go
  internal/translator/utils/rules.go
  internal/translator/utils/rules_test.go
Labels: documentation, enhancement, tests
